extends RefCounted
# GENEROWANE przez tools/bake_audio.py — nie edytuj ręcznie.
# Tablica ścieżek + flagi pętli. Runtime ładuje leniwie (load) i cache'uje.

const PATHS := {
	"alarm_bell": "res://audio/sfx/world/alarm_bell.wav",
	"amb_air": "res://audio/amb/amb_air.wav",
	"amb_drips": "res://audio/amb/amb_drips.wav",
	"amb_forest": "res://audio/amb/amb_forest.wav",
	"amb_machine": "res://audio/amb/amb_machine.wav",
	"amb_wind": "res://audio/amb/amb_wind.wav",
	"breath_loop": "res://audio/sfx/player/breath_loop.wav",
	"door_1": "res://audio/sfx/world/door_1.wav",
	"door_2": "res://audio/sfx/world/door_2.wav",
	"dry_fire": "res://audio/sfx/weapons/dry_fire.wav",
	"effort_1": "res://audio/sfx/player/effort_1.wav",
	"effort_2": "res://audio/sfx/player/effort_2.wav",
	"explosion_1": "res://audio/sfx/weapons/explosion_1.wav",
	"explosion_2": "res://audio/sfx/weapons/explosion_2.wav",
	"flare_ignite": "res://audio/sfx/world/flare_ignite.wav",
	"flare_loop": "res://audio/sfx/world/flare_loop.wav",
	"generator_loop": "res://audio/sfx/world/generator_loop.wav",
	"glass_break_1": "res://audio/sfx/world/glass_break_1.wav",
	"glass_break_2": "res://audio/sfx/world/glass_break_2.wav",
	"heart_fast_loop": "res://audio/sfx/player/heart_fast_loop.wav",
	"heart_slow_loop": "res://audio/sfx/player/heart_slow_loop.wav",
	"impact_flesh_1": "res://audio/sfx/weapons/impact_flesh_1.wav",
	"impact_flesh_2": "res://audio/sfx/weapons/impact_flesh_2.wav",
	"impact_flesh_3": "res://audio/sfx/weapons/impact_flesh_3.wav",
	"impact_hard_1": "res://audio/sfx/weapons/impact_hard_1.wav",
	"impact_hard_2": "res://audio/sfx/weapons/impact_hard_2.wav",
	"impact_hard_3": "res://audio/sfx/weapons/impact_hard_3.wav",
	"land_hard": "res://audio/sfx/player/land_hard.wav",
	"m83_shot_1": "res://audio/sfx/weapons/m83_shot_1.wav",
	"m83_shot_2": "res://audio/sfx/weapons/m83_shot_2.wav",
	"m83_shot_3": "res://audio/sfx/weapons/m83_shot_3.wav",
	"m83_shot_4": "res://audio/sfx/weapons/m83_shot_4.wav",
	"maczeta_1": "res://audio/sfx/weapons/maczeta_1.wav",
	"maczeta_2": "res://audio/sfx/weapons/maczeta_2.wav",
	"mine_beep_loop": "res://audio/sfx/world/mine_beep_loop.wav",
	"mus_chase": "res://audio/music/mus_chase.wav",
	"mus_combat": "res://audio/music/mus_combat.wav",
	"mus_silence": "res://audio/music/mus_silence.wav",
	"mus_tension": "res://audio/music/mus_tension.wav",
	"oc_load": "res://audio/sfx/ui/oc_load.wav",
	"p64_shot_1": "res://audio/sfx/weapons/p64_shot_1.wav",
	"p64_shot_2": "res://audio/sfx/weapons/p64_shot_2.wav",
	"p64_shot_3": "res://audio/sfx/weapons/p64_shot_3.wav",
	"player_down": "res://audio/sfx/player/player_down.wav",
	"player_hurt_1": "res://audio/sfx/player/player_hurt_1.wav",
	"player_hurt_2": "res://audio/sfx/player/player_hurt_2.wav",
	"radio_beep": "res://audio/sfx/world/radio_beep.wav",
	"radio_static_loop": "res://audio/sfx/world/radio_static_loop.wav",
	"reload_1": "res://audio/sfx/weapons/reload_1.wav",
	"reload_2": "res://audio/sfx/weapons/reload_2.wav",
	"reload_3": "res://audio/sfx/weapons/reload_3.wav",
	"revive": "res://audio/sfx/player/revive.wav",
	"ricochet_1": "res://audio/sfx/weapons/ricochet_1.wav",
	"ricochet_2": "res://audio/sfx/weapons/ricochet_2.wav",
	"stalker_appear": "res://audio/sfx/stalker/stalker_appear.wav",
	"stalker_growl_1": "res://audio/sfx/stalker/stalker_growl_1.wav",
	"stalker_growl_2": "res://audio/sfx/stalker/stalker_growl_2.wav",
	"stalker_shriek_1": "res://audio/sfx/stalker/stalker_shriek_1.wav",
	"stalker_shriek_2": "res://audio/sfx/stalker/stalker_shriek_2.wav",
	"stalker_step_1": "res://audio/sfx/stalker/stalker_step_1.wav",
	"stalker_step_2": "res://audio/sfx/stalker/stalker_step_2.wav",
	"stalker_step_3": "res://audio/sfx/stalker/stalker_step_3.wav",
	"stalker_whisper_loop": "res://audio/sfx/stalker/stalker_whisper_loop.wav",
	"step_concrete_1": "res://audio/sfx/player/step_concrete_1.wav",
	"step_concrete_2": "res://audio/sfx/player/step_concrete_2.wav",
	"step_concrete_3": "res://audio/sfx/player/step_concrete_3.wav",
	"step_dirt_1": "res://audio/sfx/player/step_dirt_1.wav",
	"step_dirt_2": "res://audio/sfx/player/step_dirt_2.wav",
	"step_dirt_3": "res://audio/sfx/player/step_dirt_3.wav",
	"step_metal_1": "res://audio/sfx/player/step_metal_1.wav",
	"step_metal_2": "res://audio/sfx/player/step_metal_2.wav",
	"step_metal_3": "res://audio/sfx/player/step_metal_3.wav",
	"step_water_1": "res://audio/sfx/player/step_water_1.wav",
	"step_water_2": "res://audio/sfx/player/step_water_2.wav",
	"step_water_3": "res://audio/sfx/player/step_water_3.wav",
	"sting_chase": "res://audio/music/sting_chase.wav",
	"sting_tension": "res://audio/music/sting_tension.wav",
	"tape_stop": "res://audio/sfx/world/tape_stop.wav",
	"ui_click": "res://audio/sfx/ui/ui_click.wav",
	"ui_confirm": "res://audio/sfx/ui/ui_confirm.wav",
	"ui_deny": "res://audio/sfx/ui/ui_deny.wav",
	"warn_pulse": "res://audio/sfx/ui/warn_pulse.wav",
	"whizz_1": "res://audio/sfx/weapons/whizz_1.wav",
	"whizz_2": "res://audio/sfx/weapons/whizz_2.wav",
	"whizz_3": "res://audio/sfx/weapons/whizz_3.wav",
}

# Klucze, które muszą się zapętlać (nie mogą mieć fade-outu).
const LOOPS := [
	"amb_air",
	"amb_drips",
	"amb_forest",
	"amb_machine",
	"amb_wind",
	"breath_loop",
	"flare_loop",
	"generator_loop",
	"heart_fast_loop",
	"heart_slow_loop",
	"mine_beep_loop",
	"mus_chase",
	"mus_combat",
	"mus_silence",
	"mus_tension",
	"radio_static_loop",
	"stalker_whisper_loop",
]

# Warstwy muzyki adaptacyjnej — w tej kolejności nakładają się (kumulatywne: cisza ⊂ napięcie ⊂ walka ⊂ pościg).
const MUSIC_STEMS := ["mus_silence", "mus_tension", "mus_combat", "mus_chase"]

# Sugerowane czasy przejścia w sekundach (asymetryczne celowo).
const MUSIC_BLEND := [4.0, 1.6, 0.7, 0.35]
