extends RefCounted
## Misja 1.2 „Przerwa w Nadawaniu" (GDD §9, Strefa I): uruchom 4 generatory radiostacji rozrzucone po całej mapie →
## nadajnik rozbrzmiewa na cały las (skok Uwagi, Stalker idzie na źródło) → ekstrakcja z powrotem na początek.
## Cel poboczny: Uwaga poniżej 40 do ostatniego generatora. Dane mapy dla level.gd; legenda znaczników w level.gd.
## Rozmiar 288 × 56 kafli (v2: dłuższa i trudniejsza niż pierwsza wersja 168 × 44; v3: głęboki tunel drezyny; 4 dolne wiersze to litej skały — zapas dla kamery, żeby drezyna nie chowała się pod HUD).
##
## Układ (od zachodu): skraj lasu ze startem → dziedziniec z watahą i Wołkiem → chata radiowa (generator 1, dwa Ślepce,
## antresola z kuszą, rusztowanie na dach) → bagno z szopą (Skoczki, Ćma, Mimik na rozstaju) → wieża widokowa nad
## podziemną halą (generator 2, Wołek, Ślepiec, dom Stalkera, dwa szyby) → pompownia o dwóch kondygnacjach
## (generator 3 na piętrze, Wołek na parterze) → maszt z pomostem (generator 4). Po nadawaniu: szyb przy maszcie →
## głęboki tunel (wiersze 44-51) → DREZYNA (znacznik D) jedzie torem na zachód do wyjścia E (pompuj [E] na pokładzie).
## Mapa jest generowana programem pomocniczym — po zmianach uruchom `--maptest`.

const Weapons := preload("res://scripts/weapons.gd")

const ID := "z1_m2"
const TITLE := "1.2  RADIO SILENCE"
const OBJECTIVE := "generators"
const RADIO := []
const RACKS := false                      ## true: każde „g" dostaje stojak (zbrojownia)
const AMBIENT := Color(0, 0, 0, 0)         ## kolor ciemności mapy; alfa 0 = domyślny z lights.gd
const BRIEF := "Start all four radio generators spread across the map, then escape through the deep tunnel on the handcar. Bonus: keep Attention under 40 until the last one."
const ENEMY_HP := 1.25                    ## mnożnik HP wrogów tej mapy (dłuższa i trudniejsza misja)
const UNDERGROUND_ROW := 30
## Broń na ziemi („g") od lewej: strzelba na dziedzińcu, kusza (cicha — pasuje do celu pobocznego) na antresoli chaty, kilof przy wieży nad podziemną halą
## (rozbija zamurowane przejście „q" w lewej ścianie hali: skrytka ze złomem i amunicją; wejście 3 kafle, wiersze 37-39).
const WEAPONS := [Weapons.SRUT8, Weapons.CIEGNO6, Weapons.KILOF]
const ACCENTS := [[Vector2(152, 416), 6], [Vector2(184, 416), 6], [Vector2(648, 416), 7], [Vector2(2000, 416), 7], [Vector2(3500, 416), 7]]

const MAP := [
	"##........................................................................................................................................................................................................................................................................ww..................##",
	"##........................................................................................................................................................................................................................................................................ww..................##",
	"##........................................................................................................................................................................................................................................................................ww..................##",
	"##........................................................................................................................................................................................................................................................................ww..................##",
	"##........................................................................................................................................................................................................................................................................ww..................##",
	"##........................................................................................................................................................................................................................................................................ww..................##",
	"##........................................................................................................................................................................................................................................................................ww..................##",
	"##........................................................................................................................................................................................................................................................................ww..................##",
	"##........................................................................................................................................................................................................................................................................ww..................##",
	"##........................................................................................................................................................................................................................................................................ww..................##",
	"##........................................................................................................................................................................................................................................................................ww..................##",
	"##........w...w.......................w...............w.w...............................................w.....................................w...w.w.............................w.......................................................................................ww............w.....##",
	"##........w...w.......................w...............w.w...............................................w.....................................w...w.w.............................w.......................................................................................ww............w.....##",
	"##........w...w.......................w...............w.w...............................................w.....................................w...w.w.............................w.......................................................................................ww............w.....##",
	"##........w...w.......................w...............w.w...............................................w.....................................w...w.w.............................w.......................................................................................ww............w.....##",
	"##........w...w.......................w...............w.w...............................................w.....................................w...w.w.............................w.......................................................................................ww............w.....##",
	"##........w...w.......................w...............w.w...............................................w.....................................w...w.w.............................w.....................................CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC...................ww............w.....##",
	"##........w...w.......................w...............w.w...............................................w.....................................w...w.w.............................w.....................................CbbbbbbbbbbbbbbbbbbbbbbbbbbbbbC.................G.ww............w.....##",
	"##........w...w.......................w...............w.w.........CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC...w.....................................w...w.w.............................w.....................................CbbbbbbbbbbbbbbbbbbbbbbbbbbbbbC...........============..........w.....##",
	"##........w...w.......................w...............w.w.........CbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbC...w.....................................w...w.w.......................P.....w.....................................CbbbbbbbbbbbbbbbbbbbbbbbbbbbbbC...................ww............w.....##",
	"##........w...w.......................w...............w.w.....----CbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbC...w.......CCCCCCCCCCCCCCCCCCCCC.........w...w.w.............===============.w.....................................CbbbbbbbbbbbbbbbbbbbbbbbbbbbbbC.........----......ww............w.....##",
	"##........w...w.......................w...............w.w.........CbbbbbbbbbbbbbgbbbbbbbbbbbbbbbbbbbC...w.......w...................w.........w...w.w...............w..........w..w.....................................CbbbbbbbbbbbbbbbJbbbGbbbbbPbbbC...................ww............w.....##",
	"##........w...w.......................w...............w.w...----...bbb=====================bbbbbbbbb....w.......w...................w.........w...w.w...........----w..........w..w......................................bbbbbbCCCCCCCCCCCCCCCCCCCCCCC........----........ww............w.....##",
	"##........w...w.......................w...............w.w..........bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb....w.......w...................w.........w...w.w...............w..........w..w......................................bbbbbbbbbbbbbbbbbbbbbbbbbbbbb....................ww............w.....##",
	"##........w...w.......####............w...............w.w.----.....b====bbbbbbbbbbbbbbbbbbbbbbbbbbbb....w.......w...................w.........w...w.w.........----..w..........w..w......................................b----bbbbbbbbbbbbbbbbbbbbbbbb......----..........ww............w.....##",
	"##...S..S.w...w.....########......g.kkw.a...T.T.T.T..kwow.W........bbbbbbbbbLbbbbbbLbbbbbbbbkbGbbPab.u..w...T..Tw.T...J..ok.Z...J...w.........Y...W.w...........g...w..........w..w................k.....................bbbbbbbbbbbWbbbbbbbTbbbTbbbkb................T...Twa.T.........W.P...##",
	"##################################################################CCCCCCCCCCCCCCCCCCOOOOCCCCCCCCCCCCC#####mmmmmmmmmmmmm#######~~~~~~~~~~~~~#############bbbbbb#################################################bbbbbb###CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC#########################bbbbbb##########",
	"##############################################################################################################################~~~~~~~~~~~~~#############bbbbbb#################################################bbbbbb###########################################################bbbbbb##########",
	"########################################################################################################################################################======#################################################======###########################################################======##########",
	"########################################################################################################################################################bbbbbb#################################################bbbbbb###########################################################bbbbbb##########",
	"######################################################################################################################################################CCbb====CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC====bbCC#########################################################bb====##########",
	"######################################################################################################################################################CbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbC#########################################################bbbbbb##########",
	"######################################################################################################################################################Cb====bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb====bC#########################################################====bb##########",
	"######################################################################################################################################################CbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbC#########################################################bbbbbb##########",
	"######################################################################################################################################################Cbbb====bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb====bbbC#########################################################bb====##########",
	"######################################################################################################################################################CbbbbbbbbbbbbbbbbbbbPbbbbbbbbbbbbbbbbbbbbbbbbbPbbbbbbbbbbbbbbbbbC#########################################################bbbbbb##########",
	"######################################################################################################################################################Cb====bbbbbb===============bbbbbbbbbbbbb===============bbbb====bC#########################################################====bb##########",
	"###############################################################################################################################################bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbC#########################################################bbbbbb##########",
	"###############################################################################################################################################bbbbbbbbbbb====bbbbbb====bbbbbbbbbbbbbbbbbbbb====bbbbbbbbbbbbbbb====bbbC#########################################################bb====##########",
	"###############################################################################################################################################bbubaubqbbbbbbbabbbbubbTbbTbbbLbbbbbbGbbkkbWbbbbbbbbTbbbbabbXbbubbbbbbbC#########################################################bbbbbb##########",
	"######################################################################################################################################################CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC#########################################################====bb##########",
	"############################################################bbbbbbbbbbbbbbbbbbb###################################################bbbbbbbbbbbbbbbbbbbbb#################################################bbbbbbbbbbbbbbbbb#######################################################bbbbbb##########",
	"############################################################bbbbbbbbbbbbbbbbbbb###################################################bbbbbbbbbbbbbbbbbbbbb#################################################bbbbbbbbbbbbbbbbb#######################################################bb====##########",
	"############################################################bbbbbbbbbbbbbbbbbbb###################################################bbbbbbbbbbbbbbbbbbbbb#################################################bbbbbbbbbbbbbbbbb#######################################################bbbbbb##########",
	"########CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCbbbbbbbbbbbbbbbbbbbCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCbbbbbbbbbbbbbbbbbbbbbCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCbbbbbbbbbbbbbbbbbCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC====bbCCCC######",
	"########CbbbbbbbbbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbbC######",
	"########Cbbbbbbbbbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwb====bbbC######",
	"########Cbbbbbbbbbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbb==w======bwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbb==w=======wbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbbC######",
	"########Cbbbbbbbbbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbb====bbbbbC######",
	"########CbbbbbbbbbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbwbbbbbbbbC######",
	"########CbbbbbEbbbbbbbbbwbbbbbabwbPbbubbwbbbbbbbwbTbTbTbwbbbbbbbZbbbbbJbwbbbLbbbwbbbbbWbwbbbbbbbwbbbTbTbwbbbbbbbwbbbbubbPbabbbbbwbbbbbbbJbbbZbbbJbbbbbbbwbbbbbbbwbbbbbTbTbTbbbbbwbbbbbbbwbWbbbbbwbbbbbbbwbbbbbbbJbbbbbZbwbbbbbbbwbTbTbbbwbbbbbbbwbbbLbbbwbbbbbbbwbbbbbabwbDbbubbwb====bbbC######",
	"########CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC######",
	"################################################################################################################################################################################################################################################################################################",
	"################################################################################################################################################################################################################################################################################################",
	"################################################################################################################################################################################################################################################################################################",
	"################################################################################################################################################################################################################################################################################################",
]
